
import * as mongoose from 'mongoose';

const Schema = mongoose.Schema;

export const testsaleforcepathapiSchema = new Schema({
   created_date: { type: Date, default: Date.now },
   created_by: { type: String },
   last_modified_by: { type: String },
   last_modified_date: { type: Date, default: Date.now },
   attributes: { type: String } ,
   Id: { type: String } ,
   IsDeleted: { type: String } ,
   MasterRecordId: { type: String } ,
   Name: { type: String } ,
   Type: { type: String } ,
   ParentId: { type: String } ,
   BillingStreet: { type: String } ,
   BillingCity: { type: String } ,
   BillingState: { type: String } ,
   BillingPostalCode: { type: String } ,
   BillingCountry: { type: String } ,
   BillingLatitude: { type: String } ,
   BillingLongitude: { type: String } ,
   BillingGeocodeAccuracy: { type: String } ,
   BillingAddress: { type: String } ,
   ShippingStreet: { type: String } ,
   ShippingCity: { type: String } ,
   ShippingState: { type: String } ,
   ShippingPostalCode: { type: String } ,
   ShippingCountry: { type: String } ,
   ShippingLatitude: { type: String } ,
   ShippingLongitude: { type: String } ,
   ShippingGeocodeAccuracy: { type: String } ,
   ShippingAddress: { type: String } ,
   Phone: { type: String } ,
   Fax: { type: String } ,
   AccountNumber: { type: String } ,
   Website: { type: String } ,
   PhotoUrl: { type: String } ,
   Sic: { type: String } ,
   Industry: { type: String } ,
   AnnualRevenue: { type: String } ,
   NumberOfEmployees: { type: String } ,
   Ownership: { type: String } ,
   TickerSymbol: { type: String } ,
   Description: { type: String } ,
   Rating: { type: String } ,
   Site: { type: String } ,
   OwnerId: { type: String } ,
   CreatedDate: { type: String } ,
   CreatedById: { type: String } ,
   LastModifiedDate: { type: String } ,
   LastModifiedById: { type: String } ,
   SystemModstamp: { type: String } ,
   LastActivityDate: { type: String } ,
   LastViewedDate: { type: String } ,
   LastReferencedDate: { type: String } ,
   Jigsaw: { type: String } ,
   JigsawCompanyId: { type: String } ,
   CleanStatus: { type: String } ,
   AccountSource: { type: String } ,
   DunsNumber: { type: String } ,
   Tradestyle: { type: String } ,
   NaicsCode: { type: String } ,
   NaicsDesc: { type: String } ,
   YearStarted: { type: String } ,
   SicDesc: { type: String } ,
   DandbCompanyId: { type: String } ,
   OperatingHoursId: { type: String } ,
   CustomerPriority__c: { type: String } ,
   SLA__c: { type: String } ,
   Active__c: { type: String } ,
   NumberofLocations__c: { type: String } ,
   UpsellOpportunity__c: { type: String } ,
   SLASerialNumber__c: { type: String } ,
   SLAExpirationDate__c: { type: String } 
})

const salesforceModel = mongoose.model('testsaleforcepathapi', testsaleforcepathapiSchema, 'testsaleforcepathapi');
export default salesforceModel;
