
export interface testsaleforcepathapi 
{
   created_date: { type: Date },
   created_by: { type: String },
   last_modified_by: { type: String },
   last_modified_date: { type: Date },
   attributes: null,
   Id: null,
   IsDeleted: null,
   MasterRecordId: null,
   Name: null,
   Type: null,
   ParentId: null,
   BillingStreet: null,
   BillingCity: null,
   BillingState: null,
   BillingPostalCode: null,
   BillingCountry: null,
   BillingLatitude: null,
   BillingLongitude: null,
   BillingGeocodeAccuracy: null,
   BillingAddress: null,
   ShippingStreet: null,
   ShippingCity: null,
   ShippingState: null,
   ShippingPostalCode: null,
   ShippingCountry: null,
   ShippingLatitude: null,
   ShippingLongitude: null,
   ShippingGeocodeAccuracy: null,
   ShippingAddress: null,
   Phone: null,
   Fax: null,
   AccountNumber: null,
   Website: null,
   PhotoUrl: null,
   Sic: null,
   Industry: null,
   AnnualRevenue: null,
   NumberOfEmployees: null,
   Ownership: null,
   TickerSymbol: null,
   Description: null,
   Rating: null,
   Site: null,
   OwnerId: null,
   CreatedDate: null,
   CreatedById: null,
   LastModifiedDate: null,
   LastModifiedById: null,
   SystemModstamp: null,
   LastActivityDate: null,
   LastViewedDate: null,
   LastReferencedDate: null,
   Jigsaw: null,
   JigsawCompanyId: null,
   CleanStatus: null,
   AccountSource: null,
   DunsNumber: null,
   Tradestyle: null,
   NaicsCode: null,
   NaicsDesc: null,
   YearStarted: null,
   SicDesc: null,
   DandbCompanyId: null,
   OperatingHoursId: null,
   CustomerPriority__c: null,
   SLA__c: null,
   Active__c: null,
   NumberofLocations__c: null,
   UpsellOpportunity__c: null,
   SLASerialNumber__c: null,
   SLAExpirationDate__c: null
}
